version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: main
    assignees: ["brokenpip3"]
    groups:
      python:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: main
    assignees: ["brokenpip3"]
    groups:
      actions:
        patterns:
          - "*"
