repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: detect-private-key
  - id: check-json
  - id: check-yaml
    args:
     - --unsafe

# https://stackoverflow.com/a/69979812
- repo: local
  hooks:
  - id: pytest-check
    name: pytest-check
    types: [python]
    files: ^jcli/
    entry: pytest -v -s .
    language: system
    pass_filenames: false
