name: push to PyPI

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/jenkins-job-cli
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.8"
    - name: Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.4.2
        virtualenvs-create: true
        virtualenvs-in-project: true
    - name: Install deps and build
      run: |
        poetry install --no-interaction --no-root
        poetry build
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
